-- CreateTable
CREATE TABLE "DP3" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "employeeId" TEXT NOT NULL,
    "tahunId" TEXT NOT NULL,
    "statusDP3Id" TEXT NOT NULL,
    "kualitasKerjaNilai" INTEGER NOT NULL,
    "kualitasKerjaAlasan" TEXT,
    "kehadiranDanKedisiplinanNilai" INTEGER NOT NULL,
    "kehadiranDanKedisiplinanAlasan" TEXT,
    "kerjasamaTimNilai" INTEGER NOT NULL,
    "kerjasamaTimAlasan" TEXT,
    "komitmenVisiMisiNilai" INTEGER NOT NULL,
    "komitmenVisiMisiAlasan" TEXT,
    "pengembanganDiriNilai" INTEGER NOT NULL,
    "pengembanganDiriAlasan" TEXT,
    "penggunaanTeknologiNilai" INTEGER NOT NULL,
    "penggunaanTeknologiAlasan" TEXT,
    "ketaatanKepatuhanNilai" INTEGER NOT NULL,
    "ketaatanKepatuhanAlasan" TEXT,
    "komunikasiEfektifNilai" INTEGER NOT NULL,
    "komunikasiEfektifAlasan" TEXT,
    "inisiatifProblemSolvingNilai" INTEGER NOT NULL,
    "inisiatifProblemSolvingAlasan" TEXT,
    "jumlah" INTEGER NOT NULL,
    "rataRata" INTEGER NOT NULL,
    "bobot" INTEGER NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "DP3_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "DP3_tahunId_fkey" FOREIGN KEY ("tahunId") REFERENCES "Year" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "DP3_statusDP3Id_fkey" FOREIGN KEY ("statusDP3Id") REFERENCES "StatusDP3" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
